Pk/MDP-188-Header
garySiladi/chat-project pull request #10
Opened 2019-04-30 13:55 UTC by PavolKiss

2019-05-02 13:02 UTC, pggl requested changes

2019-05-02 13:02 UTC, pggl commented on src/Router.tsx
> +      <Header path="header" />
why is Header component here?

2019-05-02 13:02 UTC, pggl commented on package.json
> +    "postcss-import": "^12.0.1",
have you merge the master branch?

2019-05-02 13:02 UTC, pggl commented on src/components/Header/header.tsx
> +const Header: FC<RouteComponentProps> = () => (
remove RouteComponentProps and FC

2019-05-02 13:02 UTC, pggl commented on src/components/Header/header.tsx
> +export default Header;
filename should have Capital letter

2019-05-02 13:02 UTC, pggl commented on src/components/Header/menu.tsx
> +export default Menu;
filename should have capital letter

2019-05-02 13:02 UTC, pggl commented on src/components/Header/navigation.tsx
> +export default Navigation;
filename should have capital letter

2019-05-02 13:02 UTC, pggl commented on src/components/Header/ImageHeader.tsx
> +  width?: number;
if this is optional we need some default value

2019-05-02 13:02 UTC, pggl commented on src/components/Header/UserButton.tsx
> +const UserButton = () => (
I think this component have bad name, there are links here

2019-05-02 13:02 UTC, pggl commented on src/components/Header/UserButton.tsx
> +    <div className="flex flex-col overflow-auto z-10 absolute">
extract this into separate component

2019-05-02 13:02 UTC, pggl commented on src/components/Header/UserMenu.tsx
> +    <div className="font-gilbert font-bold text-lg">FS</div>
we need props for this "FS"

2019-05-02 13:02 UTC, pggl commented on src/components/Header/UserProfile.tsx
> +      Feri Schwartzeneger
we need props for this name

2019-05-02 13:02 UTC, pggl commented on src/components/Header/UserProfile.tsx
> +    <div className="text-blue font-lato text-xs font-bold">Kredit 10 €</div>
also here for credit

2019-05-02 13:02 UTC, pggl commented on src/components/Header/imageHeader.tsx
> +export default ImageHeader;
old imageHeader is still there delete it

2019-05-02 13:02 UTC, pggl commented on src/components/Testing.tsx
> +import Header from "./Header/Header";
remove this

2019-05-02 13:02 UTC, pggl commented on src/components/Testing.tsx
> +const Testing: FC<RouteComponentProps> = () => <Header />;
remove this and add `<div>testing</div>`

2019-05-06 11:33 UTC, garySiladi commented on src/style/custom.css
> +}
can you add a newline at the end of the file

2019-05-07 11:20 UTC, garySiladi submitted a review, later dismissed
fine by me, contact Peter for a re-review

2019-05-07 20:15 UTC, pggl requested changes

2019-05-07 20:15 UTC, pggl commented on src/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
revert this change

2019-05-08 14:54 UTC, PavolKiss commented on src/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
reverted.

2019-05-09 08:10 UTC, pggl approved these changes
Good work

2019-05-09 08:10 UTC, merged