MDP-184: Universal Popup Component
garySiladi/chat-project pull request #11
Opened 2019-05-02 08:23 UTC by OlehVynnyk

https://velocity.globallogic.com/jira/browse/MDP-184

2019-05-02 08:57 UTC, pggl requested changes

2019-05-02 08:57 UTC, pggl commented on src/components/InfoMessage/InfoMessage.tsx
> +  text?: string;
text props is required always so remove ?

2019-05-02 08:57 UTC, pggl commented on src/components/Message/Message.tsx
> +  text?: string;
text is required

2019-05-02 08:57 UTC, pggl commented on src/components/PopupButton/PopupButton.tsx
> +  text?: string;
text is required

2019-05-02 08:57 UTC, pggl commented on src/components/PopupButton/PopupButton.tsx
> +export default ModalButton;
component name is not same as filename

2019-05-02 08:57 UTC, pggl commented on src/components/PopupsMobile/PopupsMobile.tsx
> +const StyledWrapper: React.CSSProperties = {
use better name for variable

2019-05-02 08:57 UTC, pggl commented on src/components/PopupsMobile/PopupsMobile.tsx
> +const Wrapper: React.CSSProperties = {
use destruction for CSSProperties

2019-05-02 08:57 UTC, pggl commented on src/components/Testing.tsx
> +const Testing: FC<RouteComponentProps> = () => <PopupsMobile />;
after development remove component so component will be empty

2019-05-02 08:57 UTC, pggl commented on tailwind.js
> +    gilbert: ["Gilbert", "serif"],
discard all changes in this file

2019-05-02 08:57 UTC, pggl commented on src/components/PopupsMobile/PopupsMobile.tsx
> +    <div style={Wrapper} className="flex flex-col justify-between">
is this div necessary?

2019-05-03 12:23 UTC, pggl requested changes

2019-05-03 12:23 UTC, pggl commented on src/components/Modal/ModalButton.tsx
> +  text?: string;
is text optional if so where is default value

2019-05-03 12:23 UTC, pggl commented on src/components/Modal/ModalStorybook/DisprovePopup.tsx
> +export default DisprovePopup;
I think cancel reservation is better name

2019-05-03 12:23 UTC, pggl commented on src/components/Modal/ModalStorybook/ErrorPopup.tsx
> +export default ErrorModal;
is ErrorModal same as DisprovePopup?

2019-05-03 12:23 UTC, pggl commented on src/components/Modal/ModalStorybook/KreditPopup.tsx
> +import Modal from "../MainModal";
Rename it, we use Popup, we don't want to have to two names Modal and Popup

2019-05-03 12:23 UTC, pggl commented on src/components/Modal/ModalStorybook/RegistrationPopup.tsx
> +export default ErrorModal;
component name and filename is not same

2019-05-03 12:23 UTC, pggl commented on src/components/Modal/TextUnderButton.tsx
> +const TextUnderbutton = () => (
we need props for text

2019-05-03 12:23 UTC, pggl commented on src/styles/colors.ts
> +export const pinkyPurple = "#db3eb1";
why are those colors here? we have already defined colors in our app

2019-05-06 11:17 UTC, garySiladi requested changes

2019-05-06 11:17 UTC, garySiladi commented on src/components/Popup/MainPopup.tsx
> +const MainPopup: FC = props => (
could use destructuring props as `const MainPopup: FC = ({ children }) => (`

2019-05-06 11:17 UTC, garySiladi commented on src/components/Popup/PopupButton.tsx
> +    <button className={`bg-${backgroundColor} h-10 w-5/6 rounded-lg  `}>
delete space on the end of the classname

2019-05-06 11:17 UTC, garySiladi commented on src/components/Popup/PopupStorybook/KreditPopup.tsx
> +const KreditPopup = () => (
rename kredit to credit, as grammatically correct in english

2019-05-06 11:17 UTC, garySiladi commented on src/components/Popup/XButton.tsx
> +const XButton = () => (
could rename this to `CloseButton`

2019-05-06 11:36 UTC, garySiladi requested changes

2019-05-06 11:36 UTC, garySiladi commented on src/components/Popup/Storybook/CreditPopup.tsx
> +const KreditPopup = () => (
could you rename this to `CreditPopup`?

2019-05-06 11:36 UTC, garySiladi commented on src/components/Popup/CloseButton.tsx
> +  <div className="flex justify-end ">
remove space in the end of className

2019-05-06 11:36 UTC, garySiladi commented on src/components/Popup/CloseButton.tsx
> +    <button className=" bg-black font-bold w-10 h-10 rounded-lg mr-4 ">
remove space in the end of className

2019-05-07 10:58 UTC, garySiladi submitted a review, later dismissed
nice work

2019-05-07 20:11 UTC, pggl requested changes

2019-05-07 20:11 UTC, pggl commented on src/components/Popup/Index.tsx
> +export const Index: FC = ({ children }) => (
rename it to Popup, if there will be default it is ok to filename should be index.tsx but not with **capital letter**

2019-05-09 07:58 UTC, pggl approved these changes
good work

2019-05-09 08:00 UTC, merged