Footer
garySiladi/chat-project pull request #2
Opened 2019-04-11 12:43 UTC by erikruszinka

2019-04-11 12:50 UTC, garySiladi commented on src/components/icons/Cogs.tsx
> +import React, { FunctionComponent } from "react";
I would change the file structure of these /icons/something.tsx files. Seems to me very repetitive, and contains the same div with img in it. I would create a universal icon component which receives a style, and src prop.

2019-04-11 13:01 UTC, garySiladi requested changes

2019-04-11 13:01 UTC, garySiladi commented on src/components/footer/FooterMobile.tsx
> +  <div>
why the div?

2019-04-11 13:01 UTC, garySiladi commented on src/components/footer/FooterDesktop.tsx
> +    <div style={{ width: "1024px" }}>
this div isn't needed, as the parent has the same width

2019-04-11 13:01 UTC, garySiladi commented on src/components/footer/FooterDesktop.tsx
> +import React, { FC } from "react";
we need one component for mobile and desktop, take care of differences in css.

2019-04-11 13:01 UTC, garySiladi commented on src/components/footer/ChatLogo.tsx
> +const GilbertBold = styled.div`
name this after the font but purpose. like `LogoHeader`

2019-04-11 13:01 UTC, garySiladi commented on src/components/footer/ChatLogo.tsx
> +import test from "../static/svg/icon-power-off.svg";
what is this?

2019-04-11 13:01 UTC, garySiladi commented on src/components/footer/ChatLogo.tsx
> +  font-color: #333333;
use const colors

2019-04-11 13:01 UTC, garySiladi commented on src/components/footer/ChatLocation.tsx
> +  width: 145px;
could have em or percentages rather than px.

2019-04-11 13:01 UTC, garySiladi commented on src/components/footer/ChatLocation.tsx
> +    </InlineDiv>{" "}
{" "}  isn't needed. solve with css

2019-04-11 13:01 UTC, garySiladi commented on src/components/footer/ChatLocation.tsx
> +  font-weight: normal;
isn't these `normal` values redundant, as inherited from parents?

2019-04-11 13:01 UTC, garySiladi commented on src/components/footer/ChatICO.tsx
> +      <LatoBold>OZ CHAT - Centrum pre kreatívnu liečbu Arteterapiou</LatoBold>
don't name tag after font name

2019-04-11 13:08 UTC, Stephaaan requested changes
Please fix the things written in rewiew

2019-04-11 13:08 UTC, Stephaaan commented on src/components/footer/ChatLocation.tsx
> +      <br />
Don't use `<br/>` tags
fix everywhere

2019-04-11 13:08 UTC, Stephaaan commented on src/components/footer/ChatLogo.tsx
> +  font-color: #333333;
font color hardcoded 
in future - use value from colors.ts file

2019-04-11 13:08 UTC, Stephaaan commented on src/components/footer/ChatICO.tsx
> +import { RouteComponentProps } from "@reach/router";
don't use RouteComponentProps, make own interface
use RouteComponentProps just in a components which are children of Router component from @reach/router

2019-04-11 13:08 UTC, Stephaaan commented on src/components/footer/ChatICO.tsx
> +const Lato = styled.div`
repeating component code
what about creating a component once and importing it?

2019-04-11 13:08 UTC, Stephaaan commented on src/components/footer/ChatContacts.tsx
> +const InlineDiv = styled.div`
use more meaningful name without element name in it

2019-04-11 13:08 UTC, Stephaaan commented on src/components/footer/FooterMobile.tsx
> +import ChatLocation from "./ChatContacts";
importing chatlocation from chatcontacts???

2019-04-11 13:08 UTC, Stephaaan commented on src/components/footer/FooterMobile.tsx
> +import ChatContacts from "./ChatLocation";
importing chatcontacts from chatlocation???

2019-04-11 13:08 UTC, Stephaaan commented on src/components/icons/Cogs.tsx
> +import React, { FunctionComponent } from "react";
use shorthand version of import of FunctionCode (FC) everywhere

2019-04-11 13:08 UTC, Stephaaan commented on src/components/icons/Email.tsx
> +      style={{ paddingBottom: "-18px", paddingRight: "8px" }}
use custom styled component for positioning the image (if it's possible)

2019-04-11 16:16 UTC, pggl requested changes

2019-04-11 16:16 UTC, pggl commented on src/components/footer/ChatContacts.tsx
> +const ContactsContainer = styled.div`
you don't need to write "Contacts" It's ChatContact component and the component is used only here so container for naming is good

2019-04-11 16:16 UTC, pggl commented on src/components/footer/ChatContacts.tsx
> +const ChatContacts: FC<RouteComponentProps> = () => (
RouteComponentProps is necessary only for components which are used for Routing

2019-04-11 16:16 UTC, pggl commented on src/components/footer/ChatICO.tsx
> +const LatoBold = styled.div`
this type of components is reusable, don't write it again and again

2019-04-11 16:16 UTC, pggl commented on src/components/footer/ChatLogo.tsx
> +  <div>
unnecessary div

2019-04-11 16:16 UTC, pggl commented on src/components/footer/FooterDesktop.tsx
> +const FooterDiv = styled.div`
I think better name is wrapper or container

2019-04-11 16:16 UTC, pggl commented on src/components/icons/Cogs.tsx
> +  <div>
unnecessary div

2019-04-11 16:16 UTC, pggl commented on src/components/icons/FullCheckbox.tsx
> +import styled from "@emotion/styled";
why is here this import?

2019-04-17 12:30 UTC, garySiladi commented on src/Router.tsx
> +import Footer from "./components/footer/Footer";
name the component `Footer.js` to `index.js` in the `footer` folder. That way the import will be simpler `"./components/footer"`

2019-04-23 17:54 UTC, pggl requested changes

2019-04-23 17:54 UTC, pggl commented on src/Router.tsx
> +      <Footer path="footer" />
remove this it doesn't have to be in the final code

2019-04-23 17:54 UTC, pggl commented on src/Router.tsx
> +      <Footer path="footer" />
and also remove import

2019-04-23 17:54 UTC, pggl commented on src/components/Button.tsx
> +const Button: FC<IProps> = ({ text, backgroundColor = "black" }) => (
why is there this component ?

2019-04-23 17:54 UTC, pggl commented on src/components/Icon.tsx
> +  children?: ReactNode;
you don't need children it is already in FC

2019-04-23 17:54 UTC, pggl commented on src/components/footer/Contacts.tsx
> +      <div className="font-lato text-xs color-black">chatkosice@gmail.com</div>
if there is email make proper html

2019-04-23 17:54 UTC, pggl commented on src/components/footer/Location.tsx
> +const ChatLocation = () => (
file name is Location and component is ChatLocation I think this is not ok

2019-04-23 17:54 UTC, pggl commented on src/components/footer/Logo.tsx
> +const ChatLogo = () => (
filename and component name is not same

2019-04-23 17:54 UTC, pggl commented on src/components/footer/index.tsx
> +const Footer: FC<RouteComponentProps> = () => (
remove RouteComponentProps

2019-04-23 17:54 UTC, pggl commented on src/main.css
> +html,
remove this file, reset css is already in code

2019-04-23 17:54 UTC, pggl commented on src/stories/index.tsx
> +storiesOf("Footer", module).add("responsive footer", () => <Footer />);
there should be two versions, desktop and mobile

2019-04-24 09:36 UTC, pggl requested changes

2019-04-24 09:36 UTC, pggl commented on src/components/footer/Info.tsx
> +`;
remove this and you style instead

2019-04-24 09:36 UTC, pggl commented on src/components/footer/Location.tsx
> +`;
remove this and you style instead

2019-05-02 12:00 UTC, closed without merging