MDP-189: Hamburger menu
garySiladi/chat-project pull request #20
Opened 2019-05-15 12:06 UTC by PavolKiss

2019-05-15 15:03 UTC, pggl requested changes

2019-05-15 15:03 UTC, pggl commented on src/components/Header/Header.tsx
> +  const [openMenu, setOpenMenu] = useState("closed");
why you use "closed" and "open" and not boolean for this

2019-05-15 15:03 UTC, pggl commented on src/components/Header/ImageHeader.tsx
> +  className = "",
use classnames library, it is already in master branch

2019-05-15 15:03 UTC, pggl commented on src/components/Header/ImageHeader.tsx
> +  onClick
do we need this here?

2019-05-16 12:09 UTC, garySiladi requested changes

2019-05-16 12:09 UTC, garySiladi commented on src/components/Header/ImageHeader.tsx
> +import classnames from "classnames";
we don't need the `classnames` package in this file, as the prop `className` is the only source of class here.

2019-05-16 12:09 UTC, garySiladi commented on src/components/Header/ImageHeader.tsx
> +  <img src={src} width={width} className={classnames(className)} />
this should be then `className={className}`

2019-05-16 12:09 UTC, garySiladi commented on src/components/Header/ImageHeader.tsx
>  export const ImageHeader: FC<IProps> = ({ src, width = "auto", className }) => (
set empty string as default value of className

2019-05-16 12:09 UTC, garySiladi commented on src/components/Header/Header.tsx
> +      {openMenu === true && (
you can check if `openMenu` is explicitly `true` just with the expression
```
{openMenu && (...
```

2019-05-16 12:09 UTC, garySiladi commented on src/static/svg/times.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24">
why is this image called `times` if it's a close button?

2019-05-16 12:09 UTC, garySiladi commented on src/components/Header/Header.tsx
> +        <Menu onClick={() => setOpenMenu(true)} />
as I tried this in browser, I would like to have pointer cursor and some hover effect when I hover over this icon from a design standpoint

2019-05-16 12:09 UTC, garySiladi commented on src/components/Header/Header.tsx
> +            className="opacity-75 bg-darkblue h-full w-full lg:hidden"
is the darkblue showing for you in the browser? for me it's white

2019-05-17 20:27 UTC, garySiladi approved these changes
ok from my side

2019-05-20 10:32 UTC, pggl approved these changes

2019-05-20 10:32 UTC, merged