Pk header
garySiladi/chat-project pull request #3
Opened 2019-04-12 10:37 UTC by PavolKiss

2019-04-29 11:37 UTC, garySiladi requested changes
my findings for now

2019-04-29 11:37 UTC, garySiladi commented on package.json
> +    "src": "^1.1.2"
this `src` package isn't used. probably an unwanted install

2019-04-29 11:37 UTC, garySiladi commented on src/components/Button.tsx
> +import React, { FC } from "react";
this component isn't needed

2019-04-29 11:37 UTC, garySiladi commented on src/components/Testing.tsx
> +// import styled from "@emotion/styled";
remove comments and create a route for the `Header` until a layout is written

2019-04-29 11:37 UTC, garySiladi commented on src/main.css
> +html,
this file already exists in `reset.css`

2019-04-29 13:35 UTC, pggl requested changes

2019-04-29 13:35 UTC, pggl commented on src/stories/index.tsx
> +storiesOf("Header", module).add("responsive header", () => <Header />);
add responsive version

2019-04-29 13:35 UTC, pggl commented on src/components/Testing.tsx
> +    {/* <Wrapper>
remove this, it is only for development

2019-04-29 13:35 UTC, pggl commented on src/components/Header/imageHeader.tsx
> +}
only classname and src are necessary

2019-05-02 10:47 UTC, pggl requested changes

2019-05-02 10:47 UTC, pggl commented on src/components/Header/header.tsx
> +export default Header;
filename should be with capital letter

2019-05-02 10:47 UTC, pggl commented on package.json
> +    "postcss-import": "^12.0.1",
have you merge master into current branch? because this is in the master branch

2019-05-02 10:47 UTC, pggl commented on src/components/Header/userProfile.tsx
> +    <h4 className="h-5 font-gilbert">Feri Schwartzeneger</h4>
why h4 and h6 tag?

2019-05-02 10:47 UTC, pggl commented on src/components/Header/userMenu.tsx
> +    <h3 className="font-gilbert">FS</h3>
why h3 tag?

2019-05-02 10:47 UTC, pggl commented on src/components/Testing.tsx
> +const Testing: FC<RouteComponentProps> = () => <Header />;
after development remove this, this should by empty div

2019-05-02 10:47 UTC, pggl commented on src/stories/index.tsx
> +  <div className="lg:w-full">
create component for this

2019-05-02 10:51 UTC, closed without merging