MDP-210:Create "article" component
garySiladi/chat-project pull request #36
Opened 2019-05-24 12:21 UTC by kolesarovakristina

2019-05-28 08:55 UTC, garySiladi requested changes

2019-05-28 08:55 UTC, garySiladi commented on src/components/Homepage/LandingPageWrapper.tsx
> +import { DescAndButton } from "../Description/DescrAndButton";
the filename is `descr` but the component contains `desc`

2019-05-28 08:55 UTC, garySiladi commented on src/components/Description/DescrAndButton.tsx
> +    {isLogged ? (
as we are repeating a lot of the same things, we could have a variable object according to the `isLogged` like
```
const { descriptionText, buttonText } = {
        descriptionText: isLogged
          ? "Pri viacmesačnom predpladtnom zľava až 20%"
          : "Vyskúšajte si CHAT. Registrujte sa a získajte prvú hodinu zdarma.",
        buttonText: isLogged ? "Nákup kreditov" : "Registrovať sa"
      };
```
^ and then just use the variables `descriptionText` and `buttonText` in the render

2019-05-28 08:55 UTC, garySiladi commented on src/components/Description/DescrAndButton.tsx
> +  isLogged?: boolean;
rename this to `isLoggedIn`

2019-05-28 08:55 UTC, garySiladi commented on src/components/ArticleByCategory/AllArticles.tsx
> +import React from "react";
I would rename this file to ArticlesCollection

2019-05-28 08:55 UTC, garySiladi commented on src/components/ArticleByCategory/AllArticles.tsx
> +import React from "react";
also rename the folder `ArticleByCategory` to `ArticlesCollection`

2019-06-03 08:31 UTC, garySiladi requested changes

2019-06-03 08:31 UTC, garySiladi commented on src/components/ArticlesCollection/Container.tsx
> +`;
empty line after the const here

2019-06-03 08:31 UTC, garySiladi commented on src/components/ArticlesCollection/ArticlesCollection.tsx
> +export const AllArticles = () => {
I see the file was renamed 👍the const itself should be the same `ArticlesCollection`

2019-06-03 08:31 UTC, garySiladi commented on src/index.html
> +</html>
any reason for this?

2019-06-03 16:37 UTC, pggl requested changes

2019-06-03 16:37 UTC, pggl commented on src/components/ArticlesCollection/Container.tsx
> +  padding-bottom: 20px;
use tailwind for this

2019-06-03 16:37 UTC, pggl commented on src/components/Homepage/LandingPageWrapper.tsx
> +import { DescrAndButton } from "../Description/DescrAndButton";
why this name? what is Descr?

2019-06-03 16:37 UTC, pggl commented on src/stories/index.tsx
> +  <Container />
if the name is ArticleByCategory why component have this name?

2019-06-05 11:20 UTC, garySiladi commented
fix conflicts first

2019-06-06 18:00 UTC, pggl requested changes

2019-06-06 18:00 UTC, pggl commented on src/Router.tsx
> +import { Home } from "./components/Home/index";
why is here index?

2019-06-06 18:00 UTC, pggl commented on src/components/Description/Description.tsx
> +  <h1 className="font-gilbert text-45" style={{ lineHeight: "57px" }}>
create custom tailwind for lineHeight

2019-06-06 18:00 UTC, pggl commented on src/components/Description/DescriptionAndButton.tsx
> +  isLoggedIn?: boolean;
if this is optional add default value

2019-06-06 18:00 UTC, pggl commented on src/components/Description/DescriptionAndButton.tsx
> +  };
refactor this

2019-06-06 18:00 UTC, pggl commented on src/components/Description/DescriptionAndButton.tsx
> +  };
```
const descriptionText = isLoggedIn
  ? "Pri viacmesačnom predpladtnom zľava až 20%"
  : "Vyskúšajte si CHAT. Registrujte sa a získajte prvú hodinu zdarma.";

const buttonText = isLoggedIn ? "Nákup kreditov" : "Registrovať sa";```

2019-06-06 18:00 UTC, pggl commented on src/index.html
> +</html>
revert this

2019-06-06 18:00 UTC, pggl commented on src/stories/index.tsx
> +  <Container />
still wrong name for this Component

2019-06-17 07:38 UTC, Stephaaan submitted a review, later dismissed

2019-06-17 07:38 UTC, Stephaaan commented on index.html
> -    <script src="src/index.tsx"></script>
why did you changed this in index.html? Has it a special reason?

2019-06-17 07:38 UTC, Stephaaan commented on src/components/Description/DescriptionWrapper.tsx
> +    <div className="w-full m-auto text-center descriptionLineHeight pt-96 pb-96 pr-8 pl-8 lg:w-2/3">
what about using class leading-57 instead of creating a new class?

2019-06-17 07:38 UTC, Stephaaan commented on src/style/custom.css
> +.descriptionLineHeight {
we should have class for this in tailwind

2019-06-17 07:38 UTC, Stephaaan commented on src/components/Description/DescriptionAndButton.tsx
> +  const buttonText = isLoggedIn ? "Nákup kreditov" : "Registrovať sa";
we don't need this variable, we can do this in line 19 (where this variable is used)

2019-06-17 07:57 UTC, pggl submitted a review, later dismissed

2019-06-17 08:08 UTC, garySiladi approved these changes

2019-06-17 08:09 UTC, merged