Modal update
garySiladi/chat-project pull request #37
Opened 2019-05-29 10:59 UTC by OlehVynnyk

2019-05-30 08:12 UTC, slavomircesla requested changes
components/Popup/Button.tsx
Change /rounded-8/ to /rounded-12/

2019-05-30 08:43 UTC, slavomircesla commented on src/components/Popup/InfoMessage.tsx
> +    className="mt-16 mr-48 ml-24 font-lato text-16"
only change to mt-20

2019-05-30 08:51 UTC, slavomircesla submitted a review, later dismissed

2019-05-30 12:04 UTC, garySiladi requested changes

2019-05-30 12:04 UTC, garySiladi commented on src/components/Popup/CloseButton.tsx
> +import iconTimes from "../../static/svg/icon-times.svg";
this should be named closeIcon

2019-05-30 12:04 UTC, garySiladi commented on src/components/Popup/Storybook/RegistrationPopup.tsx
> +      <PaymentInfo text="Cena arteterapie - 10 € " textColor="black" />
remove empty space in the end of the text string

2019-05-30 12:04 UTC, garySiladi commented on src/components/Schedule/ProgressBar.tsx
> +  if (actual === 0) {
don't we want to render a progress bar, if the reservations are empty?

2019-05-30 12:04 UTC, garySiladi commented on src/components/Schedule/ProgressBar.tsx
> +      className="border-b border-2 border-black absolute"
style this by giving background color and don't use absolute

2019-05-30 12:04 UTC, garySiladi commented on src/components/Schedule/ProgressBar.tsx
> +    <div
don't we need the grey line behind the black one as well?

2019-06-03 08:43 UTC, garySiladi commented
change the branching for this, it contains unrelated files

2019-06-03 13:11 UTC, closed without merging