refactor footer
garySiladi/chat-project pull request #39
Opened 2019-06-01 18:59 UTC by PavolKiss

2019-06-03 16:54 UTC, pggl requested changes

2019-06-03 16:54 UTC, pggl commented on src/components/Footer/Footer.tsx
> +import { Link } from "@reach/router";
we don't need router for this, this is external link

2019-06-03 16:54 UTC, pggl commented on src/components/Footer/Info.tsx
> +  bankNumber: string;
we don't need this props, this should be hardcoded we don't want to change this or reuse in different place

2019-06-03 16:54 UTC, pggl commented on src/components/Footer/Contacts.tsx
> +  email: string;
we don't need this props, this should be hardcoded we don't want to change this or reuse in different place

2019-06-06 17:51 UTC, pggl requested changes

2019-06-06 17:51 UTC, pggl commented on src/components/Footer/Contacts.tsx
> +      <Link to="mailto:chatkosice@gmail.com" className="font-lato text-10">
this should be <a> tag, Link is for internal routing

2019-06-12 08:42 UTC, slavomircesla commented on src/components/Footer/Info.tsx
> +    <div>OZ CHAT - Centrum pre kreatívnu liečbu Arteterapiou</div>
Bold text

2019-06-12 12:30 UTC, slavomircesla commented on src/components/Footer/Contacts.tsx
> +import { Link } from "@reach/router";
Not needed I suppose.

2019-06-12 12:34 UTC, slavomircesla commented on src/components/Footer/Info.tsx
> +  <div className="mt-20 ml-24 h-40 text-10 font-lato">
text-12 in zeplin?

2019-06-17 07:21 UTC, pggl approved these changes

2019-06-17 07:21 UTC, merged