MDP-199: Popup update
garySiladi/chat-project pull request #41
Opened 2019-06-03 13:11 UTC by OlehVynnyk

2019-06-03 16:32 UTC, pggl requested changes

2019-06-03 16:32 UTC, pggl commented on src/components/Popup/InfoMessage.tsx
> +    style={{ lineHeight: "1.38" }}
create custom tailwind class

2019-06-03 16:32 UTC, pggl commented on src/components/Popup/Message.tsx
> +    style={{ lineHeight: "1.1" }}
create custom tailwind class

2019-06-05 11:29 UTC, garySiladi commented
could you pull from master to update PR?

2019-06-10 08:42 UTC, pggl requested changes

2019-06-10 08:42 UTC, pggl commented on src/components/Popup/InfoMessage.tsx
> +    style={{ lineHeight: "1.38" }}
why this is not solved?

2019-06-13 12:58 UTC, slavomircesla approved these changes

2019-06-17 07:24 UTC, pggl approved these changes

2019-06-17 07:24 UTC, merged